-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 09, 2023 at 12:13 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `insertdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `sanpham`
--

CREATE TABLE `sanpham` (
  `maSP` int(11) NOT NULL,
  `maNhom` varchar(20) DEFAULT NULL,
  `tenSP` varchar(100) NOT NULL,
  `thongtinSP` text NOT NULL,
  `hinhanh` varchar(255) DEFAULT NULL,
  `mausac` varchar(20) NOT NULL,
  `kichthuoc` varchar(20) NOT NULL,
  `dungluong` varchar(10) NOT NULL,
  `soLuongBan` int(11) NOT NULL,
  `soHienCo` int(11) NOT NULL,
  `nhaSX` varchar(50) NOT NULL,
  `tinhtrang` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `sanpham`
--

INSERT INTO `sanpham` (`maSP`, `maNhom`, `tenSP`, `thongtinSP`, `hinhanh`, `mausac`, `kichthuoc`, `dungluong`, `soLuongBan`, `soHienCo`, `nhaSX`, `tinhtrang`) VALUES
(1, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14black.jpg', 'Đen', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(2, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14black.jpg', 'Đen', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(3, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14black.jpg', 'Đen', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(4, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14blue.jpg', 'Xanh', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(5, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14blue.jpg', 'Xanh', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(6, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14blue.jpg', 'Xanh', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(7, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14purple.jpg', 'Tím', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(8, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14purple.jpg', 'Tím', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(9, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14purple.jpg', 'Tím', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(10, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14red.jpg', 'Đỏ', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(11, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14red.jpg', 'Đỏ', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(12, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14red.jpg', 'Đỏ', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(13, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14twhite.jpg', 'Trắng', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(14, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14twhite.jpg', 'Trắng', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(15, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14twhite.jpg', 'Trắng', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(16, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14yellow.jpg', 'Vàng', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(17, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14yellow.jpg', 'Vàng', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(18, 'Phone', 'iPhone 14', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14yellow.jpg', 'Vàng', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(19, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14black.jpg', 'Đen', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(20, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14black.jpg', 'Đen', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(21, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14black.jpg', 'Đen', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(22, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14blue.jpg', 'Xanh', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(23, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14blue.jpg', 'Xanh', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(24, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14blue.jpg', 'Xanh', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(25, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14purple.jpg', 'Tím', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(26, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14purple.jpg', 'Tím', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(27, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14purple.jpg', 'Tím', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(28, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14red.jpg', 'Đỏ', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(29, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14red.jpg', 'Đỏ', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(30, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14red.jpg', 'Đỏ', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(31, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14twhite.jpg', 'Trắng', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(32, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14twhite.jpg', 'Trắng', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(33, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14twhite.jpg', 'Trắng', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(34, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14yellow.jpg', 'Vàng', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(35, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14yellow.jpg', 'Vàng', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(36, 'Phone', 'iPhone 14 Plus', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14yellow.jpg', 'Vàng', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(37, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(38, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(39, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(40, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(41, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(42, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(43, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(44, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(45, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(46, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(47, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(48, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(49, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(50, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(51, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(52, 'Phone', 'iPhone 14 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(53, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(54, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(55, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(56, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pblack.png', 'Đen', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(57, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(58, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(59, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(60, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pgray.png', 'Bạc', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(61, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(62, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(63, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(64, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Ppurple.png', 'Tím', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(65, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(66, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(67, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(68, 'Phone', 'iPhone 14 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '14Pyellow.jpg', 'Vàng', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(69, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphoneseden.jpg', 'Đen', '4,7\"', '64GB', 0, 100, 'Apple', 'Còn hàng'),
(70, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphoneseden.jpg', 'Đen', '4,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(71, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphoneseden.jpg', 'Đen', '4,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(72, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphonesedo.jpg', 'Đỏ', '4,7\"', '64GB', 0, 100, 'Apple', 'Còn hàng'),
(73, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphonesedo.jpg', 'Đỏ', '4,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(74, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphonesedo.jpg', 'Đỏ', '4,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(75, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphonesetrang.jpg', 'Trắng', '4,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(76, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphonesetrang.jpg', 'Trắng', '4,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(77, 'Phone', 'iPhone SE', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'iphonesetrang.jpg', 'Trắng', '4,7\"', '64GB', 0, 100, 'Apple', 'Còn hàng'),
(78, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13den.jpg', 'Đen', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(79, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13den.jpg', 'Đen', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(80, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13den.jpg', 'Đen', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(81, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13do.jpg', 'Đỏ', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(82, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13do.jpg', 'Đỏ', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(83, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13do.jpg', 'Đỏ', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(84, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13hong.jpg', 'Hồng', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(85, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13hong.jpg', 'Hồng', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(86, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13hong.jpg', 'Hồng', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(87, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13trang.jpg', 'Trắng', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(88, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13trang.jpg', 'Trắng', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(89, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13trang.jpg', 'Trắng', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(90, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanh.jpg', 'Xanh lam', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(91, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanh.jpg', 'Xanh lam', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(92, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanh.jpg', 'Xanh lam', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(93, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanhl.jpg', 'Xanh lục', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(94, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanhl.jpg', 'Xanh lục', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(95, 'Phone', 'iPhone 13', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanhl.jpg', 'Xanh lục', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(96, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13den.jpg', 'Đen', '5,4\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(97, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13den.jpg', 'Đen', '5,4\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(98, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13den.jpg', 'Đen', '5,4\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(99, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13do.jpg', 'Đỏ', '5,4\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(100, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13do.jpg', 'Đỏ', '5,4\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(101, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13do.jpg', 'Đỏ', '5,4\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(102, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13hong.jpg', 'Hồng', '5,4\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(103, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13hong.jpg', 'Hồng', '5,4\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(104, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13hong.jpg', 'Hồng', '5,4\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(105, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13trang.jpg', 'Trắng', '5,4\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(106, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13trang.jpg', 'Trắng', '5,4\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(107, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13trang.jpg', 'Trắng', '5,4\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(108, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanh.jpg', 'Xanh lam', '5,4\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(109, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanh.jpg', 'Xanh lam', '5,4\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(110, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanh.jpg', 'Xanh lam', '5,4\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(111, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanhl.jpg', 'Xanh lục', '5,4\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(112, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanhl.jpg', 'Xanh lục', '5,4\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(113, 'Phone', 'iPhone 13 Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13xanhl.jpg', 'Xanh lục', '5,4\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(114, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(115, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(116, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(117, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(118, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(119, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(120, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(121, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(122, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(123, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(124, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(125, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(126, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(127, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(128, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(129, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(130, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,7\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(131, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,7\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(132, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,7\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(133, 'Phone', 'iPhone 13 Pro Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,7\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(134, 'Phone', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng');
INSERT INTO `sanpham` (`maSP`, `maNhom`, `tenSP`, `thongtinSP`, `hinhanh`, `mausac`, `kichthuoc`, `dungluong`, `soLuongBan`, `soHienCo`, `nhaSX`, `tinhtrang`) VALUES
(233, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(136, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(137, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pden.jpg', 'Đen', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(138, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(139, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(140, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(141, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13ptrang.jpg', 'Trắng', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(142, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(143, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(144, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(145, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pvang.jpg', 'Vàng', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(146, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(147, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(148, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(149, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanh.jpg', 'Xanh lam', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(150, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,1\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(151, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,1\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(152, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,1\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(153, '1', 'iPhone 13 Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', '13pxanhl.jpg', 'Xanh lục', '6,1\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(154, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10bac.jpg', 'Bạc', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(155, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10bac.jpg', 'Bạc', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(156, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10bac.jpg', 'Bạc', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(157, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10hong.jpg', 'Hồng', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(158, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10hong.jpg', 'Hồng', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(159, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10hong.jpg', 'Hồng', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(160, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10vang.jpg', 'Vàng', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(161, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10vang.jpg', 'Vàng', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(162, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10vang.jpg', 'Vàng', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(163, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10xanh.jpg', 'Xanh lam', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(164, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10xanh.jpg', 'Xanh lam', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(165, '2', 'iPad 10', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipad10xanh.jpg', 'Xanh lam', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(166, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairhong.jpg', 'Hồng', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(167, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairhong.jpg', 'Hồng', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(168, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairhong.jpg', 'Hồng', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(169, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairtim.jpg', 'Tím', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(170, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairtim.jpg', 'Tím', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(171, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairtim.jpg', 'Tím', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(172, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairtrang.jpg', 'Trắng', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(173, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairtrang.jpg', 'Trắng', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(174, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairtrang.jpg', 'Trắng', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(175, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairxam.jpg', 'Xám', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(176, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairxam.jpg', 'Xám', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(177, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairxam.jpg', 'Xám', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(178, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairxanh.jpg', 'Xanh lam', '10,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(179, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairxanh.jpg', 'Xanh lam', '10,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(180, '2', 'iPad Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadairxanh.jpg', 'Xanh lam', '10,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(181, '2', 'iPad Pro M2', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadprom2_12.9trang.jpg', 'Bạc', '12,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(182, '2', 'iPad Pro M2', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadprom2_12.9trang.jpg', 'Bạc', '12,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(183, '2', 'iPad Pro M2', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadprom2_12.9.jpg', 'Xám', '12,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(184, '2', 'iPad Pro M2', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadprom2_12.9.jpg', 'Xám', '12,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(185, '2', 'iPad Pro M1', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadm1_xam.jpg', 'Xám', '12,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(186, '2', 'iPad Pro M1', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadm1_xam.jpg', 'Xám', '12,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(187, '2', 'iPad Pro M1', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadm1_trang.jpg', 'Bạc', '12,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(188, '2', 'iPad Pro M1', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadm1_trang.jpg', 'Bạc', '12,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(189, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadmini xam.jpg', 'Xám', '7,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(190, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadmini xam.jpg', 'Xám', '7,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(191, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadmini xam.jpg', 'Xám', '7,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(192, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadmini xam.jpg', 'Xám', '7,9\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(193, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminihong.jpg', 'Hồng', '7,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(194, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminihong.jpg', 'Hồng', '7,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(195, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminihong.jpg', 'Hồng', '7,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(196, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminihong.jpg', 'Hồng', '7,9\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(197, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminitim.jpg', 'Tím', '7,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(198, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminitim.jpg', 'Tím', '7,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(199, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminitim.jpg', 'Tím', '7,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(200, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminitim.jpg', 'Tím', '7,9\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(201, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminivang.jpg', 'Vàng', '7,9\"', '256GB', 0, 100, 'Apple', 'Còn hàng'),
(202, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminivang.jpg', 'Vàng', '7,9\"', '512GB', 0, 100, 'Apple', 'Còn hàng'),
(203, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminivang.jpg', 'Vàng', '7,9\"', '1TB', 0, 100, 'Apple', 'Còn hàng'),
(204, '2', 'iPad Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'ipadminivang.jpg', 'Vàng', '7,9\"', '128GB', 0, 100, 'Apple', 'Còn hàng'),
(205, '3', 'Macbook Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airm2xam.jpg', 'Xám', '13\"', '512GB', 0, 50, 'Apple', 'Còn hàng'),
(206, '3', 'Macbook Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airm2xam.jpg', 'Xám', '13\"', '1TB', 0, 50, 'Apple', 'Còn hàng'),
(207, '3', 'Macbook Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airm2xam.jpg', 'Xám', '13\"', '256GB', 0, 50, 'Apple', 'Còn hàng'),
(208, '3', 'Macbook Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airm2xac.jpg', 'Bạc', '13\"', '256GB', 0, 50, 'Apple', 'Còn hàng'),
(209, '3', 'Macbook Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airm2xac.jpg', 'Bạc', '13\"', '512GB', 0, 50, 'Apple', 'Còn hàng'),
(210, '3', 'Macbook Air', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airm2xac.jpg', 'Bạc', '13\"', '1TB', 0, 50, 'Apple', 'Còn hàng'),
(211, '3', 'Macbook Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'macbookproxam.jpg', 'Xám', '16\"', '1TB', 0, 50, 'Apple', 'Còn hàng'),
(212, '3', 'Macbook Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'macbookproxam.jpg', 'Xám', '16\"', '512GB', 0, 50, 'Apple', 'Còn hàng'),
(213, '3', 'Macbook Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'prom2bac.jpg', 'Bạc', '16\"', '512GB', 0, 50, 'Apple', 'Còn hàng'),
(214, '3', 'Macbook Pro', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'prom2bac.jpg', 'Bạc', '16\"', '1TB', 0, 50, 'Apple', 'Còn hàng'),
(215, '4', 'Apple Watch', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'watch8den.jpg', 'Đen', '1,9\"', '64GB', 0, 50, 'Apple', 'Còn hàng'),
(216, '4', 'Apple Watch', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'watch8do.jpg', 'Đỏ', '1,9\"', '64GB', 0, 50, 'Apple', 'Còn hàng'),
(217, '4', 'Apple Watch', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'watch8xam.jpg', 'Xám', '1,9\"', '64GB', 0, 50, 'Apple', 'Còn hàng'),
(218, '4', 'Apple Watch', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'watchs8bac4g.jpg', 'Bạc', '1,9\"', '64GB', 0, 50, 'Apple', 'Còn hàng'),
(219, '5', 'Tai nghe Earpods', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'earpods.jpg', 'Trắng', '1,5m', '', 0, 50, 'Apple', 'Còn hàng'),
(220, '5', 'Tai nghe Airpod Max', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airpodmax.jpg', 'Đồng', '1,5m', '', 0, 50, 'Apple', 'Còn hàng'),
(221, '5', 'Tai nghe Airpod 2', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airpod2.jpg', 'Trắng', '', '', 0, 50, 'Apple', 'Còn hàng'),
(222, '5', 'Tai nghe Airpod Pro 2', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airpodpro2.jpg', 'Trắng', '', '', 0, 50, 'Apple', 'Còn hàng'),
(223, '5', 'Tai nghe Airpod 3', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'airpod3.jpg', 'Trắng', '', '', 0, 50, 'Apple', 'Còn hàng'),
(224, '5', 'Chuột Magic Mouse', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'mouse.jpg', 'Trắng', '', '', 0, 50, 'Apple', 'Còn hàng'),
(225, '5', 'Apple Pencil', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'pencil1.jpg', 'Trắng', '', '', 0, 50, 'Apple', 'Còn hàng'),
(226, '5', 'Bàn phím Magic Keyboard', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'keyboardfull.jpg', 'Trắng', 'Fullsize', '', 0, 50, 'Apple', 'Còn hàng'),
(227, '5', 'Bàn phím Magic Keyboard TKL', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'keyboardtkl.jpg', 'Trắng', 'TKL', '', 0, 50, 'Apple', 'Còn hàng'),
(228, '5', 'Dây sạc Lightning', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'lightning1m.jpg', 'Trắng', '3m', '', 0, 50, 'Apple', 'Còn hàng'),
(229, '5', 'Củ sạc Apple', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'sac.jpg\r\n', 'Trắng', '20W', '', 0, 50, 'Apple', 'Còn hàng'),
(230, '3', 'iMac', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'imachongdo.jpg', 'Hồng', '27\"', '2TB', 0, 20, 'Apple', 'Còn hàng'),
(231, '3', 'iMac', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'imacxanh.jpg', 'Xanh lam', '27\"', '2TB', 0, 20, 'Apple', 'Còn hàng'),
(232, '3', 'Mac Mini', 'Sản phẩm của Apple là những sản phẩm công nghệ hướng tới tương lai, giúp ích chúng ta trong các tác vụ, các việc trong cuộc sống hàng ngày với 1 hệ sinh thái khép kính iOS và MacOS. Sản phẩm được nhập khẩu từ công ty Apple. Được bảo hành 12 tháng theo nhà sản xuất.', 'macmini.jpg', 'Bạc', '11\"', '1TB', 0, 25, 'Apple', 'Còn hàng');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `sanpham`
--
ALTER TABLE `sanpham`
  ADD PRIMARY KEY (`maSP`),
  ADD KEY `maNhom` (`maNhom`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `sanpham`
--
ALTER TABLE `sanpham`
  MODIFY `maSP` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=233;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
